Standardized Exit Codes
Vaerys-Dawn/DiscordSailv2 pull request #8
Opened 2017-12-25 15:23 UTC by AndrielChaoti

I offer for your perusal, SAIL's exit codes reconfigured to follow a more [standardized approach](https://en.wikipedia.org/wiki/Exit_status). Apologies for making the PR to master, I didn't know where else to put it.

Here's a quick explanation of what each field means:

- `EXITCODE_NORMAL = 0`: Used when the program is shut down normally. The "Everything is Okay" alarm, so to speak.
- `EXITCODE_RESTART = 1`: _Normally a non-zero exit code is used to indicate an error,_ but using a number specifically for a builtin restart command allows you to design scripts to start the bot that work with this.
- `EXITCODE_CONF_ERROR = 2`: This exit code is proposed for when the bot reports a configuration error, and that the user should check the bot's log files to find out what went wrong.
- `EXITCODE_OTHER_ERROR = 3`: This is unused at the moment, but it could be used if the bot needs to close for any other anticipated errors.
- `EXITCODE_UNKNOWN = 255`: This one is sort of a fallback, if the program has to crash and a handler can catch it, it should exit with this. Basically, something really went wrong here, and we don't know what.

2017-12-25 15:26 UTC, AndrielChaoti commented on .idea/misc.xml
> +  <component name="ProjectRootManager" version="2" languageLevel="JDK_1_8" default="true" project-jdk-name="Oracle JDK 1.8" project-jdk-type="JavaSDK">
IntelliJ doesn't like it when the Project SDK has a different name, because it's a butthead

2017-12-26 14:43 UTC, Vaerys-Dawn requested changes

2017-12-26 14:43 UTC, Vaerys-Dawn commented on src/main/java/com/github/vaerys/main/Globals.java
> +
The above values should be stored in Constants instead.

2017-12-30 08:53 UTC, Vaerys-Dawn approved these changes

2017-12-30 08:54 UTC, merged